site_name: DeepMatch
site_description: "Android deeplink toolkit"
site_url: "https://aouledissa.com/deep-match/"
repo_url: "https://github.com/aouledissa/deep-match"
repo_name: "aouledissa/DeepMatch"
docs_dir: docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - toc.integrate
nav:
  - Overview: index.md
  - Gradle Plugin: gradle_plugin.md
  - YAML Spec: config_file.md
  - Migration Guide: migration-guide-0.2.0-alpha.md
  - Release Notes:
      - v0.2.0-alpha: release-notes/0.2.0-alpha.md
      - v0.1.0-alpha: release-notes/0.1.0-alpha.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - fenced_code
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aouledissa/DeepMatch
      name: GitHub
