[versions]
agp = "9.0.1"
kotlin = "2.3.10"
coreKtx = "1.17.0"
junit = "4.13.2"
ktxSerializationVersion = "1.10.0"
kamlVersion = "0.104.0"
kotlinPoetVersion = "2.2.0"
xmlUtilSerializationVersion = "0.91.3"
googleTruthVersion = "1.4.5"
mockkVersion = "1.14.9"
kotlinCoroutineTestVersion = "1.10.2"
robolectricVersion = "4.16.1"
binaryCompatibilityValidator = "0.18.1"
gradleupNmcp = "1.4.4"
gradlePublish = "2.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
android-gradle-api = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "ktxSerializationVersion" }
kaml = { group = "com.charleskorn.kaml", name = "kaml", version.ref = "kamlVersion" }
squareup-kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinPoetVersion" }
xmlUtil-serialization = { group = "io.github.pdvrieze.xmlutil", name = "serialization", version.ref = "xmlUtilSerializationVersion" }
google-truth = { group = "com.google.truth", name = "truth", version.ref = "googleTruthVersion" }
mockk-core = { group = "io.mockk", name = "mockk", version.ref = "mockkVersion" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinCoroutineTestVersion" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectricVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradle-plugin = { id = "java-gradle-plugin" }
java-library = { id = "java-library" }
maven-publish = { id = "maven-publish" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibilityValidator" }
gradleup-nmcp = { id = "com.gradleup.nmcp", version.ref = "gradleupNmcp" }
gradleup-nmcp-aggregation = { id = "com.gradleup.nmcp.aggregation", version.ref = "gradleupNmcp" }
gradle-publish = {id="com.gradle.plugin-publish", version.ref="gradlePublish"}
